config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: 'users/omniauth_callbacks' }
  resources  :users,       only: [:index, :show]
  resources  :users_admin
  resources  :posts
  resources  :likes,       only: [:create, :destroy]
  resources  :comments,    only: [:create, :destroy]
  resources  :friendships, only: [:create, :update, :destroy]
  resources  :notifications

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  root to: "posts#index"

end

app/models/user.rb
class User < ApplicationRecord

  after_save :convert_spaces

  enum role: [:user, :admin]

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable, :confirmable, :omniauthable,
         :omniauth_providers => [:facebook]

  act_as_mentionee

  has_many :posts,         dependent: :destroy
  has_many :comments,      dependent: :destroy
  has_many :likes,         dependent: :destroy
  has_many :friendships,   dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :active_friends,        -> { where(friendships: { accepted: true }) },
           through: :friendships, source: :friend
  has_many :received_friends,      -> { where(friendships: { accepted: true }) },
           through: :received_friendships, source: :user
  has_many :pending_friends,       -> { where(friendships: { accepted: false }) },
           through: :friendships, source: :friend
  has_many :requested_friendships, -> { where(friendships: { accepted: false }) },
           through: :received_friendships, source: :user

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", mini: "50x50>"},
                    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def set_default_role
    self.role ||= :user
  end

  def is_admin?
    self.role == "admin"
  end

  def likes?(post_id)
    liked_post_ids = []
    self.likes.each do |l|
      liked_post_ids << l.post_id
    end
    post_id.in?(liked_post_ids)
  end

  def friends
    active_friends | received_friends
  end

  def pending
    pending_friends | requested_friendships
  end

  def current_friendship
    self.friendships.find_by(user_id: self.id, friend_id: current_user.id)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name.gsub(' ', '_')   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def active_notifications
    self.notifications.where(read: false)
  end

  self.per_page = 10

  private

  def convert_spaces
    if self.username.include?(' ')
      user_name = self.username.gsub(' ', '_')
      self.update(username: user_name)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    if @user
      @posts = @user.posts.order(created_at: :desc)
    end
    if @posts
      @comment = current_user.comments.build
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to request.referrer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {}).permit(:username, :email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 100 })
    size = options[:size]
    if user.avatar.exists?
      if size > 100
        image_size = :medium
      elsif size < 100
        image_size = :mini
      else
        image_size = :thumb
      end
      image_url = user.avatar.url(image_size)
    else
      gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
      image_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
    image_tag(image_url, alt: user.username, class: "gravatar")
  end
end

app/views/users/_form.html.slim
- if user.errors.any?
  #error_explanation
    h2
      = pluralize(user.errors.count, "error")
      |  prohibited this user from being saved:
    ul
      - user.errors.full_messages.each do |message|
        li
          = message
.actions
  = f.submit

app/views/users/_user.slim
tr
  td
    = link_to( gravatar_for(user), user_path(user) )
  td
    = link_to "#{user.username}", user_path(user)
  - if user != current_user && user.in?(current_user.pending)
    td
      .fa.fa-clock-o
      |  Request pending
  - elsif user != current_user && !user.in?(current_user.friends)
    td
      = link_to "Add friend", friendships_path(friend_id: user), method: :post
  - elsif user != current_user && user.in?(current_user.friends)
    td
      .fa.fa-check-square
      |  Friends
    td.delete
      = link_to "Unfriend", friendship_path(user), method: :delete
  - elsif user == current_user
    td It's you!

app/views/users/edit.html.slim
h1
  | Editing User
= form_for @user, url: users_admin_path(@user), html: { method: :put } do |f|
  = render 'form', f: f
= link_to 'Show', @user
|  | 
= link_to 'Back', users_path

app/views/users/index.slim
- if current_user.requested_friendships.present?
  .col-md-6
    h2 Pending friend requests
    ul.pending-requests
      - current_user.received_friendships.each do |friendship|
        - if friendship.accepted == false
          li
            = friendship.user.username
            = link_to "Accept",  friendship_path(id: friendship.id), method: "put"
            = link_to "Decline", friendship_path(id: friendship.id), method: :delete, class: "delete"

.col-md-6
  h2 All users
  table
    thead
      tr
        th colspan="3"
    tbody.users
      = render @users
  = will_paginate @users

app/views/users/new.slim
h1 New User

div
= form_for @user, url: users_admin_path, html: { method: :post } do |f|
  = render 'form', f: f
  = link_to 'Back', users_admin_path

app/views/users/show.slim
.container
  aside.col-md-5.user-info
      section.user
        h1
          = gravatar_for @user
          = @user.username
        .email
          | Email: #{@user.email}
        .hometown
          | Hometown: #{@user.hometown}
        .birthday
          | Birthday: #{@user.birthday}

        - if @user != current_user && @user.in?(current_user.pending)
          td
            .fa.fa-clock-o
            |  Request pending
        - elsif @user != current_user && !@user.in?(current_user.friends)
          td
            = link_to "Add friend", friendships_path(friend_id: @user), method: :post
        - elsif @user != current_user && @user.in?(current_user.friends)
          td
            .fa.fa-check-square
            |  Friends
          td.delete
            = link_to "Unfriend", friendship_path(@user), method: :delete
        - elsif @user == current_user
          td
            = link_to "Edit profile", edit_user_registration_path(current_user)
        br
      section.friends
        h2
         | #{@user.username}'s friends
        table
          thead
            tr
              th colspan="3"
          tbody.users
            = render @user.friends

  - if @posts && current_user.in?(@user.friends) || current_user == @user
    .col-md-6.post-feed
      = render @posts