config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: 'users/omniauth_callbacks' }
  resources  :users,       only: [:index, :show]
  resources  :users_admin
  resources  :posts
  resources  :likes,       only: [:create, :destroy]
  resources  :comments,    only: [:create, :destroy]
  resources  :friendships, only: [:create, :update, :destroy]
  resources  :notifications

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  root to: "posts#index"

end

app/models/post.rb
class Post < ApplicationRecord

  after_save :create_mentions
  #after_save :create_mention_links

  validates :photo_url, presence: { if: -> {:content.blank?}},
                        format: { with: /(?:([^:\/?#]+):)?(?:\/\/([^\/?#]*))?([^?#]*\.(?:jpg|jpeg|gif|png))(?:\?([^#]*))?(?:#(.*))?/ },
                        allow_blank: :true
  validates :content,   presence: { if: -> {:photo_url.blank?}},
             length: { maximum: 5000 }

  act_as_mentioner

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  self.per_page = 10

  def create_mentions
    m = CustomMentionProcessor.new
    m.process_mentions(self)
  end

  def create_mention_links
    content_words = self.content.split(" ")
    content_with_links = content_words.map do |word|
      if word.start_with?("@")
        mention = self.mentions.where(username: word.gsub('@', '')).first if @post.mentions.present?
        link_to mention.mentionee_id, user_path(mention.mentionee_id)
      else
        word
      end
    end
    self.content = content_with_links.join(" ")
    self.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :destroy
  after_action  :mention_notifications, only: [:create, :update]

  def new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
    else
      flash[:danger] = "Error creating post. If you're trying to post a picture,
                        please make sure the link ends in a valid format."
    end
    redirect_to request.referrer
  end

  def index
    @comment = current_user.comments.build
    @post = current_user.posts.build
    @posts = Post.where(user_id: post_user_ids).paginate(:page => params[:page]).
      order(created_at: :desc)
    @photo_posts = Post.where(user_id: post_user_ids).where.not(photo_url: nil).
      limit(21).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comment = current_user.comments.build
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to root_url
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :photo_url)
  end

  def correct_user
    if current_user.is_admin?
      @post = Post.find_by_id(params[:id])
    else
      @post = current_user.posts.find_by(id: params[:id])
    end
    if @post.nil?
      flash[:danger] = "Not authorized"
      redirect_to request.referrer
    end
  end

  def post_user_ids
    ids = []
    current_user.friends.each do |f|
      ids << f.id
    end
    ids << current_user.id
  end

  def mention_notifications
    if @post.mentionees.present?
      @post.mentionees.each do |m|
        return if m.mentionee_id == current_user.id
        Notification.create(user_id: m.mentionee_id,
                            notified_by_id: current_user.id,
                            post_id: @post.id,
                            notice_type: 'post_mention')
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_photostream.slim
- if @photo_posts
  h3 Recent photos
  - @photo_posts.each do |post|
    - if post.photo_url.present?
      .col-xs-6.photo-square
        = link_to(image_tag(post.photo_url, class: ""), post)

app/views/posts/_post.slim
li class="post" id="post-#{post.id}"
  .post-user
    = link_to( gravatar_for(post.user, size: 50), "/users/#{post.user.id}")
    h4
      = link_to post.user.username, "/users/#{post.user.id}"
    .timestamp
      | Posted #{time_ago_in_words(post.created_at)} ago.
  .content-links
    .post-content
      - if post.content?
        p
          = render_with_mentions(post).html_safe
      - if post.photo_url?
        = image_tag("#{post.photo_url}", class: "img-responsive")
    br
    .like-links
      - if current_user.likes?(post.id)
        = link_to "unlike", like_path(:id => post.id), method: :delete, class: "unlike"
      - else
        = link_to "like", likes_path(:post_id => post.id), method: :post, class: "like"
    .likes
      - if post.likes.present?
        .fa.fa-thumbs-up
        |
        = post.likes.count
        .like-users
          | The following users liked this post:
          ul
            - post.likes.each do |l|
              li.like
                = link_to l.user.username, l.user
                br
    br
    - if current_user == post.user || current_user.is_admin?
      span.delete
        = link_to "delete post", post, method: :delete,
                                  data: { confirm: "You sure?" }
      span.edit
        = link_to "edit post", edit_post_path(post)
    br
    - if post.comments.present?
      .comments
        - post.comments.each do |c|
          ul.comment
            li
              = link_to "#{c.user.username}:", "/users/#{c.user.id}"
              .comment-content
                = render_with_mentions(c).html_safe
              .timestamp
                | #{time_ago_in_words(c.created_at)} ago
              .delete
                - if c.user == current_user
                  = link_to "delete comment", c, method: :delete,
                    data: { confirm: "You sure?" }
              br
  = form_for(@comment) do |f|
    .comment-fields
      = f.hidden_field :post_id, :value => post.id
      = f.text_area :content, placeholder: "Your comment goes here"
      br
      = f.submit "Comment", class: "btn btn.primary"

app/views/posts/edit.slim
.container
  .col-md-6.post-feed
    = render 'shared/post_form'

app/views/posts/index.slim
.container
  .col-md-6.post-feed
    = render 'shared/post_form'
    = render @posts
    = will_paginate @posts
  .col-md-6.photostream
    = render 'photostream'

app/views/posts/show.slim
.container
  .col-md-6.post-feed
    = render @post