config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: 'users/omniauth_callbacks' }
  resources  :users,       only: [:index, :show]
  resources  :users_admin
  resources  :posts
  resources  :likes,       only: [:create, :destroy]
  resources  :comments,    only: [:create, :destroy]
  resources  :friendships, only: [:create, :update, :destroy]
  resources  :notifications

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  root to: "posts#index"

end

app/views/layouts/_fb.slim
javascript:
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '225527874641244',
      cookie     : true,
      xfbml      : true,
      version    : 'v2.8'
    });
    FB.AppEvents.logPageView();   
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

app/views/layouts/_header.slim
.navbar.navbar-fixed-top.navbar-inverse
  .container
    nav
      #logo
        = link_to "odin-social", root_path
      ul.nav.navbar-nav.navbar-right
        - if logged_in?
          li
            = link_to "Posts", posts_path
          li
            = link_to "Users", users_path
          = render 'notifications/notification_dropdown'
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown"
              | Account
              b.caret
            ul.dropdown-menu
              li

                = link_to "Settings", edit_user_registration_path(current_user)
              li
                = link_to "Profile", "/users/#{current_user.id}"
              li.divider
              li
                = link_to "Log out", destroy_user_session_path, method: :delete
        - else
          li
            = link_to "Sign in", new_user_session_path
          li
            = link_to "Sign up", new_user_registration_path

app/views/layouts/_mobile_header.slim
.mobile-header.navbar-fixed-top
  #logo
    = link_to "odin-social", root_path
  - if logged_in?
    - if current_user.active_notifications.present?
      = link_to notifications_path
        b.notification
          = current_user.active_notifications.count

app/views/layouts/_mobile_menu.slim
ul.navigation
  li.nav-item
    = link_to "Home", root_path
  - if logged_in?
    li.nav-item
      = link_to "Posts", posts_path
    li.nav-item
      = link_to "Users", users_path
    li.nav-item
      = link_to "Settings", edit_user_registration_path(current_user)
    li.nav-item
      = link_to "Profile", "/users/#{current_user.id}"
    li.nav-item
      = link_to "Log out", destroy_user_session_path, method: :delete
  - else
    li.nav-item
      = link_to "Sign in", new_user_session_path
    li.nav-item
      = link_to "Sign up", new_user_registration_path

input.nav-trigger id="nav-trigger" type="checkbox"
label for="nav-trigger" class="fa fa-bars"

app/views/layouts/_rails_default.slim
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Odinsocial
    = render 'layouts/rails_default'
    meta name="viewport" content="width=device-width"
  body
    #top
    = render 'layouts/fb'
    = render 'layouts/header'
    = render 'layouts/mobile_menu'
    .site-wrap
      .container
        - flash.each do |message_type, message|
          div class="alert alert-#{message_type}"
            = message
      = render 'layouts/mobile_header'
      = yield
      - if Rails.env.development?
        = debug(params)
        div style="height: 300px"
        = console